name: Hello
on:
    push:
        branches: [master]

jobs:
    doHello:
        name: Hi
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Hello
              uses: ./.github/actions/hello-world
